// KIT DATA ARRAY
var namMember = new Array(
  "<img src='kits/2026/atl.png' class='kit-thumb'> |<b>Atlanta United</b>|<i>Spirit of '96</i>|",
  "<img src='kits/2026/atx.png' class='kit-thumb'> |<b>Austin FC</b>|<i>The Rooted Kit</i>|",
  "<img src='kits/2026/chi.png' class='kit-thumb'> |<b>Chicago Fire</b>|<i>Forever Red</i>|",
  "<img src='kits/2026/cin.png' class='kit-thumb'> |<b>FC Cincinnati</b>|<i>The Seven Hills Kit</i>|",
  "<img src='kits/2026/clb.png' class='kit-thumb'> |<b>Columbus Crew</b>|<i>The Crafted for Excellence Kit</i>|",
  "<img src='kits/2026/clt.png' class='kit-thumb'> |<b>Charlotte FC</b>|<i>Carolina Kit: Crowns Up</i>|",
  "<img src='kits/2026/col.png' class='kit-thumb'> |<b>Colorado Rapids</b>|<i>Colorful Colorado</i>|",
  "<img src='kits/2026/dal.png' class='kit-thumb'> |<b>FC Dallas</b>|<i>DNA Kit</i>|",
  "<img src='kits/2026/dcu.png' class='kit-thumb'> |<b>D.C. United</b>|<i>Black-and-Red Kit</i>|",
  "<img src='kits/2026/hou.png' class='kit-thumb'> |<b>Houston Dynamo FC</b>|<i>Mission Control</i>|",
  "<img src='kits/2026/lafc.png' class='kit-thumb'> |<b>LAFC</b>|<i>Primary Kit</i>|",
  "<img src='kits/2026/lag.png' class='kit-thumb'> |<b>LA Galaxy</b>|<i>The VeloCITY Kit</i>|",
  "<img src='kits/2026/mia.png' class='kit-thumb'> |<b>Inter Miami CF</b>|<i>Presagio</i>|",
  "<img src='kits/2026/min.png' class='kit-thumb'> |<b>Minnesota United FC</b>|<i>The Decade Kit</i>|",
  "<img src='kits/2026/mtl.png' class='kit-thumb'> |<b>CF Montréal</b>|<i>The Procure Jersey</i>|",
  "<img src='kits/2026/ne.png' class='kit-thumb'> |<b>New England Revolution</b>|<i>Independence Day</i>|",
  "<img src='kits/2026/nsh.png' class='kit-thumb'> |<b>Nashville SC</b>|<i>The Reverb Kit</i>|",
  "<img src='kits/2026/nyc.png' class='kit-thumb'> |<b>New York City FC</b>|<i>The All Nations Kit</i>|",
  "<img src='kits/2026/nyrb.png' class='kit-thumb'> |<b>New York Red Bulls</b>|<i>The Rooted Kit</i>|",
  "<img src='kits/2026/orl.png' class='kit-thumb'> |<b>Orlando City SC</b>|<i>Sunken Treasure Kit</i>|",
  "<img src='kits/2026/phi.png' class='kit-thumb'> |<b>Philadelphia Union</b>|<i>1776 Kit</i>|",
  "<img src='kits/2026/por.png' class='kit-thumb'> |<b>Portland Timbers</b>|<i>Civic Stadium Kit</i>|",
  "<img src='kits/2026/rsl.png' class='kit-thumb'> |<b>Real Salt Lake</b>|<i>The Switchback</i>|",
  "<img src='kits/2026/sd.png' class='kit-thumb'> |<b>San Diego FC</b>|<i>Unprecedented Unity Kit</i>|",
  "<img src='kits/2026/sea.png' class='kit-thumb'> |<b>Seattle Sounders FC</b>|<i>The Evergreen State Kit</i>|",
  "<img src='kits/2026/sj.png' class='kit-thumb'> |<b>San Jose Earthquakes</b>|<i>The Dead Kit</i>|",
  "<img src='kits/2026/skc.png' class='kit-thumb'> |<b>Sporting Kansas City</b>|<i>The 18th & Vine Kit</i>|",
  "<img src='kits/2026/stl.png' class='kit-thumb'> |<b>St. Louis CITY SC</b>|<i>The Tina Turner Kit</i>|",
  "<img src='kits/2026/tor.png' class='kit-thumb'> |<b>Toronto FC</b>|<i>Winter Kit</i>|",
  "<img src='kits/2026/van.png' class='kit-thumb'> |<b>Vancouver Whitecaps FC</b>|<i>The Coastal</i>|"
);
